
SET NOCOUNT ON

INSERT INTO AutomailerParameterMaster (AutomailerId,ParameterIndex,ParameterName,ParameterDisplayname,IsSoftDelete)VALUES(1,1,'USR_NM','User Name',0)
INSERT INTO AutomailerParameterMaster (AutomailerId,ParameterIndex,ParameterName,ParameterDisplayname,IsSoftDelete)VALUES(1,2,'CRS_NM','Course Name',0)
INSERT INTO AutomailerParameterMaster (AutomailerId,ParameterIndex, ParameterName,ParameterDisplayname,IsSoftDelete)VALUES(1,3,'CRS_DSCRPTN','Description',0)
INSERT INTO AutomailerParameterMaster (AutomailerId,ParameterIndex, ParameterName,ParameterDisplayname,IsSoftDelete)VALUES(1,4,'CRS_URL','Course Url',0)

SET NOCOUNT OFF



